# Form implementation generated from reading ui file 'ui_files_latest\Page11_QuickEnd.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from resources_rc import *
main_page_image = ":images/BEST_landing_abstract.png"
side_page_image = ":images/BEST_side_abstract.png"

class Ui_Page11_QuickEnd(object):
    def setupUi(self, Page11_QuickEnd):
        Page11_QuickEnd.setObjectName("Page11_QuickEnd")
        Page11_QuickEnd.resize(1260, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Page11_QuickEnd.sizePolicy().hasHeightForWidth())
        Page11_QuickEnd.setSizePolicy(sizePolicy)
        Page11_QuickEnd.setStyleSheet("")
        self.layoutWidget = QtWidgets.QWidget(parent=Page11_QuickEnd)
        self.layoutWidget.setGeometry(QtCore.QRect(190, 650, 1051, 35))
        self.layoutWidget.setObjectName("layoutWidget")
        self.button_layout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.button_layout.setContentsMargins(0, 0, 0, 0)
        self.button_layout.setObjectName("button_layout")
        self.backBtn = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.backBtn.setObjectName("backBtn")
        self.button_layout.addWidget(self.backBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.button_layout.addItem(spacerItem)
        self.saveBtn = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.saveBtn.setObjectName("saveBtn")
        self.button_layout.addWidget(self.saveBtn)
        self.pdfBtn = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setKerning(True)
        self.pdfBtn.setFont(font)
        self.pdfBtn.setObjectName("pdfBtn")
        self.button_layout.addWidget(self.pdfBtn)
        self.page_11_group_1 = QtWidgets.QGroupBox(parent=Page11_QuickEnd)
        self.page_11_group_1.setGeometry(QtCore.QRect(650, 330, 161, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_11_group_1.sizePolicy().hasHeightForWidth())
        self.page_11_group_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        self.page_11_group_1.setFont(font)
        self.page_11_group_1.setStyleSheet("QPushButton {\n"
"    background-color: #26481f;  /* Green */\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"    border-radius: 6px;\n"
"    min-width: 90px;\n"
"    min-height: 15px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41;\n"
"}\n"
"\n"
"QPushButton#saveBtn {\n"
"                background-color: white;\n"
"                color: #26481f;\n"
"            }\n"
"QPushButton#saveBtn:hover {\n"
"                background-color: #45a049;\n"
"              color: white;\n"
"            }\n"
"\n"
"    QLineEdit {\n"
"        border-radius: 10px;    \n"
"        padding: 5px;           \n"
"    }\n"
"\n"
"myLineEdit->setFixedSize(200, 30)")
        self.page_11_group_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.page_11_group_1.setObjectName("page_11_group_1")
        self.side_image = QtWidgets.QLabel(parent=Page11_QuickEnd)
        self.side_image.setGeometry(QtCore.QRect(0, -30, 171, 761))
        self.side_image.setText("")
        self.side_image.setPixmap(QtGui.QPixmap(side_page_image))
        self.side_image.setObjectName("side_image")
        self.progressBar = QtWidgets.QProgressBar(parent=Page11_QuickEnd)
        self.progressBar.setGeometry(QtCore.QRect(200, 20, 1001, 23))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    background-color: #F0F0F0;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"}\n"
"QProgressBar::chunk {\n"
"    border-radius: 8px;\n"
"    background: QLinearGradient(\n"
"        x1: 0, y1: 0, x2: 1, y2: 0,\n"
"        stop: 0 #33bef0,   /* Light Blue */\n"
"        stop: 1 #77d695    /* Light Green */\n"
"    );\n"
"}")
        self.progressBar.setProperty("value", 95)
        self.progressBar.setObjectName("progressBar")
        self.layoutWidget_3 = QtWidgets.QWidget(parent=Page11_QuickEnd)
        self.layoutWidget_3.setGeometry(QtCore.QRect(200, 40, 1001, 22))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_12.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_12.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_12.addWidget(self.label_11, 0, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_12.addWidget(self.label_12, 0, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_12.addWidget(self.label_13, 0, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_12.addWidget(self.label_14, 0, 5, 1, 1)
        self.label_15 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_12.addWidget(self.label_15, 0, 6, 1, 1)
        self.label_16 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_12.addWidget(self.label_16, 0, 7, 1, 1)

        self.retranslateUi(Page11_QuickEnd)
        QtCore.QMetaObject.connectSlotsByName(Page11_QuickEnd)
        Page11_QuickEnd.setTabOrder(self.backBtn, self.saveBtn)
        Page11_QuickEnd.setTabOrder(self.saveBtn, self.pdfBtn)

    def retranslateUi(self, Page11_QuickEnd):
        _translate = QtCore.QCoreApplication.translate
        Page11_QuickEnd.setWindowTitle(_translate("Page11_QuickEnd", "Form"))
        self.backBtn.setText(_translate("Page11_QuickEnd", "Back"))
        self.saveBtn.setText(_translate("Page11_QuickEnd", "Save Progress"))
        self.pdfBtn.setText(_translate("Page11_QuickEnd", "Generate Report"))
        self.page_11_group_1.setTitle(_translate("Page11_QuickEnd", "End of measure evaluation"))
        self.label_3.setText(_translate("Page11_QuickEnd", "Cost and Emission"))
        self.label_10.setText(_translate("Page11_QuickEnd", "Production"))
        self.label_11.setText(_translate("Page11_QuickEnd", "Electricity Generation            "))
        self.label_12.setText(_translate("Page11_QuickEnd", "Energy Input"))
        self.label_13.setText(_translate("Page11_QuickEnd", "Target"))
        self.label_14.setText(_translate("Page11_QuickEnd", "EE Measures"))
        self.label_15.setText(_translate("Page11_QuickEnd", "Fuel Switching"))
        self.label_16.setText(_translate("Page11_QuickEnd", "Other Measures"))
